// Configuración de Gmail API
const GMAIL_CONFIG = {
  CLIENT_ID: 'TU_CLIENT_ID_AQUI',
  CLIENT_SECRET: 'TU_CLIENT_SECRET_AQUI',
  REDIRECT_URL: 'TU_REDIRECT_URL_AQUI',
  ACCESS_TOKEN: 'TU_ACCESS_TOKEN_AQUI',
  REFRESH_TOKEN: 'TU_REFRESH_TOKEN_AQUI'
};

